### PR TITLE
Added new file moons.R that lists moons. Only completed Earth moon so far

### PR DESCRIPTION
**Pull request by alexnakagawa**
Hello @DataWookie ,

My name is Alex Nakagawa, and I am a student in your iXperience Data Science class. I loved the new R Package you were developing ("**elliptical**"), and wished to contribute!

I have added a new file in the R folder titled "**moons.R**" and was able to add a specific framework for adding all of the moons in the observable solar system (very similar to your planets.R file). I hoped that this change would make your quest for modeling the entire solar system easier and more comprehensible!

Best,

Alex Nakagawa
Student - Data Science @ iXperience 20117

P.S. To explain all the formalness, I wanted to practice as if I was pitching to a developer I have never met before.

### CODE REVIEW

**Comment by DataWookie** [comment]
Hi Alex,

Very nicely done with your pull request message. You definitely got my attention and made a good first impression.

If you add in data for a few more moons then I'd be happy to accept.

Another suggestion: create a "Work to be done" section in the README file and mention that we need help adding data for moons.

Then resubmit your pull request.

Thanks,
Andrew.

**Comment by alexnakagawa** [comment]
It has been done! Let me know what you think.

Alex

**Comment by DataWookie** [comment]
Hi Alex, there's a bug in your file moons.R. Can you please fix it and update? Thanks, Andrew.

**Comment by alexnakagawa** [comment]
It seems that the build fails in the dwarf planets section, according to the details part of the travis ci build. Please confirm, because I could be wrong.

**Comment by DataWookie** [comment]
Sweet. Good work, @alexnakagawa.

**Pull request merged**
