### PR TITLE
Added the moon with its own orbit distance and eccentricity

### PR DESCRIPTION
**Pull request by Cagoeller**
Would it be alright if the moon's data would be added to the data frame, thank you for looking at this request

### CODE REVIEW

**Comment by Cagoeller** [comment]
Data was not loaded into the rdata file, I'm sorry

**Comment by DataWookie** [comment]
Good idea. alexnakagawa had a similar idea. Would you please collaborate with him? Thanks.

**Comment by DataWookie** [comment]
Any update on this?

**Comment by Cagoeller** [comment]
I've added a function that calculates the distance of the foci from the center, however I had trouble with devtools, where I  tried to use the document function and it kept giving me errors. 

Would it be alright to meet with you after class to try and figure out where it all went wrong?

Thanks, 
Cary

**Comment by Cagoeller** [comment]
I think I might have merged the files correctly, I hope this works. 

Thank you for helping me trying to figure this out.

**Pull request merged**
