### PR TITLE
I added in three more Earth-like planets into the planet section.

### PR DESCRIPTION
**Pull request by winnieyann**
Thank you!

Winnie

### CODE REVIEW

**Comment by DataWookie** [comment]
Hi,

I'm happy with the two Kepler objects but I'm not sure that the Gliese object makes sense: it's orbiting a different star. Maybe take that out and resubmit?

Thanks,
Andrew.

**Comment by DataWookie** [comment]
Hi @winnieyann, I'e accepted changes to the planets.R file which are now producing merge conflicts with your proposed changes. I'd still like to include your work. Would you please:

1. update your fork (see https://help.github.com/articles/syncing-a-fork/);
2. merge in your changes with these updates; and
3. update your pull request.

This might appear to be a whole lot of work, but it should give you a clear idea of the development process.

Thanks,
Andrew.

**Comment by DataWookie** [comment]
Any update on this?

**Comment by winnieyann** [comment]
Hi @DataWookie ! I added the two planets as well as removed a line from the DESCRIPTION file that was causing the build to fail.

For the Travis CI build, here's the error message that I received. I did some research into it and noticed that @Cagoeller 's code had added this commit history line at the bottom (see the error message below).

```Error in read.dcf(path_desc) : 
  Line starting 'e05cc46fa5805b11be6a ...' is malformed!
Calls: <Anonymous> ... as.package -> load_pkg_description -> as.list -> read.dcf
Execution halted```

Let me know if you have any questions!

Thanks,

Winnie

**Comment by DataWookie** [comment]
Thanks for your hard work on this, @winnieyann. I'm merging your changes now and adding you as a contributor.

**Pull request merged**
