### PR TITLE
Added Jupiter's Galilean Moons to planets tab

### PR DESCRIPTION
**Pull request by raghavku**
Hi Andrew,

I really liked your package on ellipses, however, I think adding my edits on the planets tab will improve it. Please have a look :)

### CODE REVIEW

**Comment by DataWookie** [comment]
Another issue that occurs to me here is that these moons are orbiting around Jupiter. Would it not make more sense to create a separate data frame for them? I mean they are not really "planets" are they?

**Comment by raghavku** [comment]
Hi Andrew,

I agree with your suggestion. I'll resubmit it as soon as I'm back from surfing :)

Have a wonderful afternoon! 
Thank you,

Raghav Kumar
University of Southern California 
LinkedIn: www.linkedin.com/raghav96kumar

**Comment by DataWookie** [comment]
Cool. Hope that the surfing was fun. No rush with this. Enjoy your weekend!

**Comment by DataWookie** [comment]
Hey!

Not sure if you tested your code but this doesn't seem right:

    planets <- transform(moons, distance = distance * 1e6 / 1.496e8)

Sure you want to assign the rest to `moons` not `planets`?

Please update and resubmit.

Thanks, Andrew.

**Comment by DataWookie** [comment]
Any update on this? Do you see the problem? You are assigning the transformed results from your `moons` variable to the `planets` variable...

**Comment by DataWookie** [comment]
Thanks, @raghavku!

**Pull request merged**
