### PR TITLE
added in perihelion procession values for all planets excluding pluto.

### PR DESCRIPTION
**Pull request by rayheberer**
Hi DataWookie! I have really enjoyed working with your package, and thought that with your planets data frame, it has the potential to be extended for astronomical applications. To this end, I have extended your data frame with observational and theoretical values for the perihelion precession of all of the planets, excluding Pluto.

### CODE REVIEW

**Comment by DataWookie** [comment]
Hi Ray,

You are such an overachiever. :) This is fantastic. One request: you would please change the column names to use "_" rather than "." for separator.

Thanks,
Andrew.

**Comment by rayheberer** [comment]
Alright it's done!

**Comment by DataWookie** [comment]
Hey! Thanks. I've accepted some pull requests which have added some other objects to this data frame. Do you think that you could find precession information for them as well? Thanks, Andrew.

**Comment by DataWookie** [comment]
Any update on this?

**Comment by rayheberer** [comment]
I'm still in the process of finding an adequate data source. RIght now observations by Elena Pitjeva seem promising. Thanks for waiting, you can expect an update tonight!

**Pull request closed without merging**
