### PR TITLE
Adding Ramanujan Estimation to perimeter function

### PR DESCRIPTION
**Pull request by aminondo**
Hello Andrew!

I am a big fan of your package and have included extra functionality that I hope you will consider. Below is a list of my changes.

Created function for perimeter estimation of ellipses using Ramanujan Estimation. 

Regards,
Antonio

### CODE REVIEW

**Comment by DataWookie** [comment]
Hi Antonio,

This is a great idea. I have a suggestion though: why not incorporate this functionality into the existing perimeter function and offer an option which specifies which technique to use. I'd prefer not to have two separate functions doing essentially the same thing.

Thanks,
Andrew.

**Comment by aminondo** [comment]
According to comments from you I have edited the perimeter function, now there is a new parameter called approx, when this is set to true, e will be taken as the semi-minor axis.

Hope you will consider it.

**Comment by DataWookie** [comment]
Hi Antonio, thanks! Okay, I'm generally happy with your changes. But I am not too comfortable with using `e` as the other length. Surely this is going to cause confusion? Someties `e` is eccentricity, other times it is a length... There must be a better way to do this. Give it some thought. I mean, if you supply the length of the semi-major axis and the eccentricity then you can **calculate** the length of the semi-minor axis and then apply the approximation. Thanks, Andrew.

**Comment by DataWookie** [comment]
Any update on this?

**Comment by aminondo** [comment]
just made a pull request.

**Comment by DataWookie** [comment]
Thanks, @aminondo!

**Pull request merged**
